### PR TITLE
Update AWS SDK, fixed GCC 9 on ubuntu 20.04

### PR DESCRIPTION
**Pull request by fran6co**
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Fixes https://github.com/aws-robotics/utils-common/issues/55

### CODE REVIEW

**Review by dabonnie — CHANGES_REQUESTED** [review]
Hi @fran6co, thanks for the PR! You'll want to fix the build failures noted on the [Travis builds](https://travis-ci.org/github/aws-robotics/utils-common/builds/744379560).

**Comment by fran6co** [comment]
Not sure why the test is failing with a segmentation fault

**Comment by dabonnie** [comment]
FYI @emersonknapp @mm318. 

I may be misremembering, but thought `utils-common` was stuck at 1.6 for Lex and Polly breaking changes. Thoughts on this PR?

**Comment by mm318** [comment]
I do remember there needed to be code changes to the Lex Cloud Extension when updating between some AWS SDK versions, and I think we've already done that once before. It may apply to this new AWS SDK version bump as well.

These particular `Build & Test` failures are unrelated to breaking changes to downstream dependencies though. However, bumping the AWS SDK version should involve some testing of downstream dependencies though.

**Comment by fran6co** [comment]
The main reason I did this PR is for porting the ROS packages to 20.04 and noetic. I only had to fix this other project -> https://github.com/aws-robotics/utils-ros1/pull/36 for it to work

**Comment by fran6co** [comment]
> Not sure why the test is failing with a segmentation fault

fixed segfault

**Comment by jikawa-az** [comment]
Following up on this, updated branch and retesting.

**Comment by jikawa-az** [comment]
@emersonknapp PTAL as well, this PR should add support for Focal which is not working for our images.

**Review by jikawa-az — APPROVED** [review]

**Review by emersonknapp — APPROVED** [review]

**Pull request merged**
